import random
import sys
import time

class WeatherStationSource:
    def __init__(self, name, avg):
        self.name = name
        self.avg = avg

class ClockNerd:
    def __init__(self, work):
        self.work = work
        self.start = time.time()
    def update(self, completed):
        def fmt(secs):
            return f"{int(secs)//60:d}m{int(secs)%60:d}s"
        print(f" {(completed / self.work) * 100:.2f}%", end="")
        if completed > 0:
            elapsed = time.time() - self.start
            unit = elapsed / completed
            total = self.work * unit
            remain = total - elapsed
            print(f" -{fmt(remain)} (of {fmt(total)})        ", end="")
        print("", end="\r", flush=True)

def generate(count, stations):
    max_record_length = max(len(ws.name) + len("-99.9\n") for ws in stations)
    max_file_size = count * max_record_length
    with open("measurements.txt", "w") as f:
        f.truncate(max_file_size)
        written = 0
        print("Generating measurements.txt...")
        nerd = ClockNerd(count)
        for i in range(count):
            if i % 1000000 == 0:
                nerd.update(i)
            station = random.choice(stations)
            measurement = station.avg + random.randint(-109, 109)
            written += f.write(f"{station.name}{measurement // 10}.{measurement % 10}\n")
        print("\r100.00%")
        f.truncate(written)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        raise ValueError("Missing parameter: number of records to create (int)")
    try:
        count = int(sys.argv[1])
    except ValueError:
        raise ValueError("Invalid parameter: number of records to create (int)")
    generate(count, [
        WeatherStationSource("Abha;", 180),
        WeatherStationSource("Abidjan;", 260),
        WeatherStationSource("Abéché;", 294),
        WeatherStationSource("Accra;", 264),
        WeatherStationSource("Addis Ababa;", 160),
        WeatherStationSource("Adelaide;", 173),
        WeatherStationSource("Aden;", 291),
        WeatherStationSource("Ahvaz;", 254),
        WeatherStationSource("Albuquerque;", 140),
        WeatherStationSource("Alexandra;", 110),
        WeatherStationSource("Alexandria;", 200),
        WeatherStationSource("Algiers;", 182),
        WeatherStationSource("Alice Springs;", 210),
        WeatherStationSource("Almaty;", 100),
        WeatherStationSource("Amsterdam;", 102),
        WeatherStationSource("Anadyr;", -69),
        WeatherStationSource("Anchorage;", 28),
        WeatherStationSource("Andorra la Vella;", 98),
        WeatherStationSource("Ankara;", 120),
        WeatherStationSource("Antananarivo;", 179),
        WeatherStationSource("Antsiranana;", 252),
        WeatherStationSource("Arkhangelsk;", 13),
        WeatherStationSource("Ashgabat;", 171),
        WeatherStationSource("Asmara;", 156),
        WeatherStationSource("Assab;", 305),
        WeatherStationSource("Astana;", 35),
        WeatherStationSource("Athens;", 192),
        WeatherStationSource("Atlanta;", 170),
        WeatherStationSource("Auckland;", 152),
        WeatherStationSource("Austin;", 207),
        WeatherStationSource("Baghdad;", 228),
        WeatherStationSource("Baguio;", 195),
        WeatherStationSource("Baku;", 151),
        WeatherStationSource("Baltimore;", 131),
        WeatherStationSource("Bamako;", 278),
        WeatherStationSource("Bangkok;", 286),
        WeatherStationSource("Bangui;", 260),
        WeatherStationSource("Banjul;", 260),
        WeatherStationSource("Barcelona;", 182),
        WeatherStationSource("Bata;", 251),
        WeatherStationSource("Batumi;", 140),
        WeatherStationSource("Beijing;", 129),
        WeatherStationSource("Beirut;", 209),
        WeatherStationSource("Belgrade;", 125),
        WeatherStationSource("Belize City;", 267),
        WeatherStationSource("Benghazi;", 199),
        WeatherStationSource("Bergen;", 77),
        WeatherStationSource("Berlin;", 103),
        WeatherStationSource("Bilbao;", 147),
        WeatherStationSource("Birao;", 265),
        WeatherStationSource("Bishkek;", 113),
        WeatherStationSource("Bissau;", 270),
        WeatherStationSource("Blantyre;", 222),
        WeatherStationSource("Bloemfontein;", 156),
        WeatherStationSource("Boise;", 114),
        WeatherStationSource("Bordeaux;", 142),
        WeatherStationSource("Bosaso;", 300),
        WeatherStationSource("Boston;", 109),
        WeatherStationSource("Bouaké;", 260),
        WeatherStationSource("Bratislava;", 105),
        WeatherStationSource("Brazzaville;", 250),
        WeatherStationSource("Bridgetown;", 270),
        WeatherStationSource("Brisbane;", 214),
        WeatherStationSource("Brussels;", 105),
        WeatherStationSource("Bucharest;", 108),
        WeatherStationSource("Budapest;", 113),
        WeatherStationSource("Bujumbura;", 238),
        WeatherStationSource("Bulawayo;", 189),
        WeatherStationSource("Burnie;", 131),
        WeatherStationSource("Busan;", 150),
        WeatherStationSource("Cabo San Lucas;", 239),
        WeatherStationSource("Cairns;", 250),
        WeatherStationSource("Cairo;", 214),
        WeatherStationSource("Calgary;", 44),
        WeatherStationSource("Canberra;", 131),
        WeatherStationSource("Cape Town;", 162),
        WeatherStationSource("Changsha;", 174),
        WeatherStationSource("Charlotte;", 161),
        WeatherStationSource("Chiang Mai;", 258),
        WeatherStationSource("Chicago;", 98),
        WeatherStationSource("Chihuahua;", 186),
        WeatherStationSource("Chișinău;", 102),
        WeatherStationSource("Chittagong;", 259),
        WeatherStationSource("Chongqing;", 186),
        WeatherStationSource("Christchurch;", 122),
        WeatherStationSource("City of San Marino;", 118),
        WeatherStationSource("Colombo;", 274),
        WeatherStationSource("Columbus;", 117),
        WeatherStationSource("Conakry;", 264),
        WeatherStationSource("Copenhagen;", 91),
        WeatherStationSource("Cotonou;", 272),
        WeatherStationSource("Cracow;", 93),
        WeatherStationSource("Da Lat;", 179),
        WeatherStationSource("Da Nang;", 258),
        WeatherStationSource("Dakar;", 240),
        WeatherStationSource("Dallas;", 190),
        WeatherStationSource("Damascus;", 170),
        WeatherStationSource("Dampier;", 264),
        WeatherStationSource("Dar es Salaam;", 258),
        WeatherStationSource("Darwin;", 276),
        WeatherStationSource("Denpasar;", 237),
        WeatherStationSource("Denver;", 104),
        WeatherStationSource("Detroit;", 100),
        WeatherStationSource("Dhaka;", 259),
        WeatherStationSource("Dikson;", -111),
        WeatherStationSource("Dili;", 266),
        WeatherStationSource("Djibouti;", 299),
        WeatherStationSource("Dodoma;", 227),
        WeatherStationSource("Dolisie;", 240),
        WeatherStationSource("Douala;", 267),
        WeatherStationSource("Dubai;", 269),
        WeatherStationSource("Dublin;", 98),
        WeatherStationSource("Dunedin;", 111),
        WeatherStationSource("Durban;", 206),
        WeatherStationSource("Dushanbe;", 147),
        WeatherStationSource("Edinburgh;", 93),
        WeatherStationSource("Edmonton;", 42),
        WeatherStationSource("El Paso;", 181),
        WeatherStationSource("Entebbe;", 210),
        WeatherStationSource("Erbil;", 195),
        WeatherStationSource("Erzurum;", 51),
        WeatherStationSource("Fairbanks;", -23),
        WeatherStationSource("Fianarantsoa;", 179),
        WeatherStationSource("Flores),  Petén;", 264),
        WeatherStationSource("Frankfurt;", 106),
        WeatherStationSource("Fresno;", 179),
        WeatherStationSource("Fukuoka;", 170),
        WeatherStationSource("Gabès;", 195),
        WeatherStationSource("Gaborone;", 210),
        WeatherStationSource("Gagnoa;", 260),
        WeatherStationSource("Gangtok;", 152),
        WeatherStationSource("Garissa;", 293),
        WeatherStationSource("Garoua;", 283),
        WeatherStationSource("George Town;", 279),
        WeatherStationSource("Ghanzi;", 214),
        WeatherStationSource("Gjoa Haven;", -144),
        WeatherStationSource("Guadalajara;", 209),
        WeatherStationSource("Guangzhou;", 224),
        WeatherStationSource("Guatemala City;", 204),
        WeatherStationSource("Halifax;", 75),
        WeatherStationSource("Hamburg;", 97),
        WeatherStationSource("Hamilton;", 138),
        WeatherStationSource("Hanga Roa;", 205),
        WeatherStationSource("Hanoi;", 236),
        WeatherStationSource("Harare;", 184),
        WeatherStationSource("Harbin;", 50),
        WeatherStationSource("Hargeisa;", 217),
        WeatherStationSource("Hat Yai;", 270),
        WeatherStationSource("Havana;", 252),
        WeatherStationSource("Helsinki;", 59),
        WeatherStationSource("Heraklion;", 189),
        WeatherStationSource("Hiroshima;", 163),
        WeatherStationSource("Ho Chi Minh City;", 274),
        WeatherStationSource("Hobart;", 127),
        WeatherStationSource("Hong Kong;", 233),
        WeatherStationSource("Honiara;", 265),
        WeatherStationSource("Honolulu;", 254),
        WeatherStationSource("Houston;", 208),
        WeatherStationSource("Ifrane;", 114),
        WeatherStationSource("Indianapolis;", 118),
        WeatherStationSource("Iqaluit;", -93),
        WeatherStationSource("Irkutsk;", 10),
        WeatherStationSource("Istanbul;", 139),
        WeatherStationSource("İzmir;", 179),
        WeatherStationSource("Jacksonville;", 203),
        WeatherStationSource("Jakarta;", 267),
        WeatherStationSource("Jayapura;", 270),
        WeatherStationSource("Jerusalem;", 183),
        WeatherStationSource("Johannesburg;", 155),
        WeatherStationSource("Jos;", 228),
        WeatherStationSource("Juba;", 278),
        WeatherStationSource("Kabul;", 121),
        WeatherStationSource("Kampala;", 200),
        WeatherStationSource("Kandi;", 277),
        WeatherStationSource("Kankan;", 265),
        WeatherStationSource("Kano;", 264),
        WeatherStationSource("Kansas City;", 125),
        WeatherStationSource("Karachi;", 260),
        WeatherStationSource("Karonga;", 244),
        WeatherStationSource("Kathmandu;", 183),
        WeatherStationSource("Khartoum;", 299),
        WeatherStationSource("Kingston;", 274),
        WeatherStationSource("Kinshasa;", 253),
        WeatherStationSource("Kolkata;", 267),
        WeatherStationSource("Kuala Lumpur;", 273),
        WeatherStationSource("Kumasi;", 260),
        WeatherStationSource("Kunming;", 157),
        WeatherStationSource("Kuopio;", 34),
        WeatherStationSource("Kuwait City;", 257),
        WeatherStationSource("Kyiv;", 84),
        WeatherStationSource("Kyoto;", 158),
        WeatherStationSource("La Ceiba;", 262),
        WeatherStationSource("La Paz;", 237),
        WeatherStationSource("Lagos;", 268),
        WeatherStationSource("Lahore;", 243),
        WeatherStationSource("Lake Havasu City;", 237),
        WeatherStationSource("Lake Tekapo;", 87),
        WeatherStationSource("Las Palmas de Gran Canaria;", 212),
        WeatherStationSource("Las Vegas;", 203),
        WeatherStationSource("Launceston;", 131),
        WeatherStationSource("Lhasa;", 76),
        WeatherStationSource("Libreville;", 259),
        WeatherStationSource("Lisbon;", 175),
        WeatherStationSource("Livingstone;", 218),
        WeatherStationSource("Ljubljana;", 109),
        WeatherStationSource("Lodwar;", 293),
        WeatherStationSource("Lomé;", 269),
        WeatherStationSource("London;", 113),
        WeatherStationSource("Los Angeles;", 186),
        WeatherStationSource("Louisville;", 139),
        WeatherStationSource("Luanda;", 258),
        WeatherStationSource("Lubumbashi;", 208),
        WeatherStationSource("Lusaka;", 199),
        WeatherStationSource("Luxembourg City;", 93),
        WeatherStationSource("Lviv;", 78),
        WeatherStationSource("Lyon;", 125),
        WeatherStationSource("Madrid;", 150),
        WeatherStationSource("Mahajanga;", 263),
        WeatherStationSource("Makassar;", 267),
        WeatherStationSource("Makurdi;", 260),
        WeatherStationSource("Malabo;", 263),
        WeatherStationSource("Malé;", 280),
        WeatherStationSource("Managua;", 273),
        WeatherStationSource("Manama;", 265),
        WeatherStationSource("Mandalay;", 280),
        WeatherStationSource("Mango;", 281),
        WeatherStationSource("Manila;", 284),
        WeatherStationSource("Maputo;", 228),
        WeatherStationSource("Marrakesh;", 196),
        WeatherStationSource("Marseille;", 158),
        WeatherStationSource("Maun;", 224),
        WeatherStationSource("Medan;", 265),
        WeatherStationSource("Mek'ele;", 227),
        WeatherStationSource("Melbourne;", 151),
        WeatherStationSource("Memphis;", 172),
        WeatherStationSource("Mexicali;", 231),
        WeatherStationSource("Mexico City;", 175),
        WeatherStationSource("Miami;", 249),
        WeatherStationSource("Milan;", 130),
        WeatherStationSource("Milwaukee;", 89),
        WeatherStationSource("Minneapolis;", 78),
        WeatherStationSource("Minsk;", 67),
        WeatherStationSource("Mogadishu;", 271),
        WeatherStationSource("Mombasa;", 263),
        WeatherStationSource("Monaco;", 164),
        WeatherStationSource("Moncton;", 61),
        WeatherStationSource("Monterrey;", 223),
        WeatherStationSource("Montreal;", 68),
        WeatherStationSource("Moscow;", 58),
        WeatherStationSource("Mumbai;", 271),
        WeatherStationSource("Murmansk;", 6),
        WeatherStationSource("Muscat;", 280),
        WeatherStationSource("Mzuzu;", 177),
        WeatherStationSource("N'Djamena;", 283),
        WeatherStationSource("Naha;", 231),
        WeatherStationSource("Nairobi;", 178),
        WeatherStationSource("Nakhon Ratchasima;", 273),
        WeatherStationSource("Napier;", 146),
        WeatherStationSource("Napoli;", 159),
        WeatherStationSource("Nashville;", 154),
        WeatherStationSource("Nassau;", 246),
        WeatherStationSource("Ndola;", 203),
        WeatherStationSource("New Delhi;", 250),
        WeatherStationSource("New Orleans;", 207),
        WeatherStationSource("New York City;", 129),
        WeatherStationSource("Ngaoundéré;", 220),
        WeatherStationSource("Niamey;", 293),
        WeatherStationSource("Nicosia;", 197),
        WeatherStationSource("Niigata;", 139),
        WeatherStationSource("Nouadhibou;", 213),
        WeatherStationSource("Nouakchott;", 257),
        WeatherStationSource("Novosibirsk;", 17),
        WeatherStationSource("Nuuk;", -14),
        WeatherStationSource("Odesa;", 107),
        WeatherStationSource("Odienné;", 260),
        WeatherStationSource("Oklahoma City;", 159),
        WeatherStationSource("Omaha;", 106),
        WeatherStationSource("Oranjestad;", 281),
        WeatherStationSource("Oslo;", 57),
        WeatherStationSource("Ottawa;", 66),
        WeatherStationSource("Ouagadougou;", 283),
        WeatherStationSource("Ouahigouya;", 286),
        WeatherStationSource("Ouarzazate;", 189),
        WeatherStationSource("Oulu;", 27),
        WeatherStationSource("Palembang;", 273),
        WeatherStationSource("Palermo;", 185),
        WeatherStationSource("Palm Springs;", 245),
        WeatherStationSource("Palmerston North;", 132),
        WeatherStationSource("Panama City;", 280),
        WeatherStationSource("Parakou;", 268),
        WeatherStationSource("Paris;", 123),
        WeatherStationSource("Perth;", 187),
        WeatherStationSource("Petropavlovsk-Kamchatsky;", 19),
        WeatherStationSource("Philadelphia;", 132),
        WeatherStationSource("Phnom Penh;", 283),
        WeatherStationSource("Phoenix;", 239),
        WeatherStationSource("Pittsburgh;", 108),
        WeatherStationSource("Podgorica;", 153),
        WeatherStationSource("Pointe-Noire;", 261),
        WeatherStationSource("Pontianak;", 277),
        WeatherStationSource("Port Moresby;", 269),
        WeatherStationSource("Port Sudan;", 284),
        WeatherStationSource("Port Vila;", 243),
        WeatherStationSource("Port-Gentil;", 260),
        WeatherStationSource("Portland (OR);", 124),
        WeatherStationSource("Porto;", 157),
        WeatherStationSource("Prague;", 84),
        WeatherStationSource("Praia;", 244),
        WeatherStationSource("Pretoria;", 182),
        WeatherStationSource("Pyongyang;", 108),
        WeatherStationSource("Rabat;", 172),
        WeatherStationSource("Rangpur;", 244),
        WeatherStationSource("Reggane;", 283),
        WeatherStationSource("Reykjavík;", 43),
        WeatherStationSource("Riga;", 62),
        WeatherStationSource("Riyadh;", 260),
        WeatherStationSource("Rome;", 152),
        WeatherStationSource("Roseau;", 262),
        WeatherStationSource("Rostov-on-Don;", 99),
        WeatherStationSource("Sacramento;", 163),
        WeatherStationSource("Saint Petersburg;", 58),
        WeatherStationSource("Saint-Pierre;", 57),
        WeatherStationSource("Salt Lake City;", 116),
        WeatherStationSource("San Antonio;", 208),
        WeatherStationSource("San Diego;", 178),
        WeatherStationSource("San Francisco;", 146),
        WeatherStationSource("San Jose;", 164),
        WeatherStationSource("San José;", 226),
        WeatherStationSource("San Juan;", 272),
        WeatherStationSource("San Salvador;", 231),
        WeatherStationSource("Sana'a;", 200),
        WeatherStationSource("Santo Domingo;", 259),
        WeatherStationSource("Sapporo;", 89),
        WeatherStationSource("Sarajevo;", 101),
        WeatherStationSource("Saskatoon;", 33),
        WeatherStationSource("Seattle;", 113),
        WeatherStationSource("Ségou;", 280),
        WeatherStationSource("Seoul;", 125),
        WeatherStationSource("Seville;", 192),
        WeatherStationSource("Shanghai;", 167),
        WeatherStationSource("Singapore;", 270),
        WeatherStationSource("Skopje;", 124),
        WeatherStationSource("Sochi;", 142),
        WeatherStationSource("Sofia;", 106),
        WeatherStationSource("Sokoto;", 280),
        WeatherStationSource("Split;", 161),
        WeatherStationSource("St. John's;", 50),
        WeatherStationSource("St. Louis;", 139),
        WeatherStationSource("Stockholm;", 66),
        WeatherStationSource("Surabaya;", 271),
        WeatherStationSource("Suva;", 256),
        WeatherStationSource("Suwałki;", 72),
        WeatherStationSource("Sydney;", 177),
        WeatherStationSource("Tabora;", 230),
        WeatherStationSource("Tabriz;", 126),
        WeatherStationSource("Taipei;", 230),
        WeatherStationSource("Tallinn;", 64),
        WeatherStationSource("Tamale;", 279),
        WeatherStationSource("Tamanrasset;", 217),
        WeatherStationSource("Tampa;", 229),
        WeatherStationSource("Tashkent;", 148),
        WeatherStationSource("Tauranga;", 148),
        WeatherStationSource("Tbilisi;", 129),
        WeatherStationSource("Tegucigalpa;", 217),
        WeatherStationSource("Tehran;", 170),
        WeatherStationSource("Tel Aviv;", 200),
        WeatherStationSource("Thessaloniki;", 160),
        WeatherStationSource("Thiès;", 240),
        WeatherStationSource("Tijuana;", 178),
        WeatherStationSource("Timbuktu;", 280),
        WeatherStationSource("Tirana;", 152),
        WeatherStationSource("Toamasina;", 234),
        WeatherStationSource("Tokyo;", 154),
        WeatherStationSource("Toliara;", 241),
        WeatherStationSource("Toluca;", 124),
        WeatherStationSource("Toronto;", 94),
        WeatherStationSource("Tripoli;", 200),
        WeatherStationSource("Tromsø;", 29),
        WeatherStationSource("Tucson;", 209),
        WeatherStationSource("Tunis;", 184),
        WeatherStationSource("Ulaanbaatar;", -4),
        WeatherStationSource("Upington;", 204),
        WeatherStationSource("Ürümqi;", 74),
        WeatherStationSource("Vaduz;", 101),
        WeatherStationSource("Valencia;", 183),
        WeatherStationSource("Valletta;", 188),
        WeatherStationSource("Vancouver;", 104),
        WeatherStationSource("Veracruz;", 254),
        WeatherStationSource("Vienna;", 104),
        WeatherStationSource("Vientiane;", 259),
        WeatherStationSource("Villahermosa;", 271),
        WeatherStationSource("Vilnius;", 60),
        WeatherStationSource("Virginia Beach;", 158),
        WeatherStationSource("Vladivostok;", 49),
        WeatherStationSource("Warsaw;", 85),
        WeatherStationSource("Washington), D.C.;", 146),
        WeatherStationSource("Wau;", 278),
        WeatherStationSource("Wellington;", 129),
        WeatherStationSource("Whitehorse;", -1),
        WeatherStationSource("Wichita;", 139),
        WeatherStationSource("Willemstad;", 280),
        WeatherStationSource("Winnipeg;", 30),
        WeatherStationSource("Wrocław;", 96),
        WeatherStationSource("Xi'an;", 141),
        WeatherStationSource("Yakutsk;", -88),
        WeatherStationSource("Yangon;", 275),
        WeatherStationSource("Yaoundé;", 238),
        WeatherStationSource("Yellowknife;", -43),
        WeatherStationSource("Yerevan;", 124),
        WeatherStationSource("Yinchuan;", 90),
        WeatherStationSource("Zagreb;", 107),
        WeatherStationSource("Zanzibar City;", 260),
        WeatherStationSource("Zürich;", 93),
    ])

